### ISSUE TITLE
package stats don't return 404s

### ISSUE THREAD

**Issue by Prouser123** [jsdelivr/data.jsdelivr.com#11]
When loading [v1/package/npm/fakepackage123](https://data.jsdelivr.com/v1/package/npm/fakepackage123), a HTTP error 404 is returned.
However, when loading [v1/package/npm/fakepackage123/stats](https://data.jsdelivr.com/v1/package/npm/fakepackage123/stats) a code 200 OK is sent, and shows no hits and a null rank.

I know that the null rank is intentional if there are no hits, but could we have it return a code 404 if the package doesn't exist?

**Comment by MartinKolarik** [comment]
Packages may be deleted (this is especially true for GitHub repos), in which case the stats would become unavailable. The CDN explicitly supports serving deleted packages so we should support getting stats for them as well.
