### ISSUE TITLE
Package size exceeded the configured limit of 50 MB

### ISSUE THREAD

**Issue by markcarver** [jsdelivr/data.jsdelivr.com#12]
https://data.jsdelivr.com/v1/package/npm/bootswatch@3.4.1/flat returns:

```
{
status: 403,
message: "Package size exceeded the configured limit of 50 MB."
}
```

This version was published 3 hours ago (at time of writing): 
https://github.com/thomaspark/bootswatch/issues/892
https://www.npmjs.com/package/bootswatch/v/3.4.1

Now I cannot imagine that it's seriously over 50 MB. Could this just be a caching issue of something gone wrong?

**Comment by styfle** [comment]
That version really is over 50MB. 

https://packagephobia.now.sh/result?p=bootswatch@3.4.1

**Comment by MartinKolarik** [comment]
There's a new `docs` directory, which I believe is responsible for the significant size increase.

**Comment by markcarver** [comment]
That appears to be the case.

I ended up just statically mapping to `3.4.0` for this specific package/version. It's a shame that this kind of mistake is now locked in the API forever.

**Comment by PatMyron** [comment]
I actually ran into this error message because I had an incorrect URL, which took a while to figure out
