### ISSUE TITLE
Question: Package Usage Stats Performance/Stability

### ISSUE THREAD

**Issue by calebcartwright** [jsdelivr/data.jsdelivr.com#13]
Hi there! We've been experiencing frequent timeout issues (eventually receiving an HTTP 524 error) with the [package usage stats api](https://github.com/jsdelivr/data.jsdelivr.com#get-package-usage-stats) when we use a value for `period` other than the default `month` 

Some times the API returns fine, but it is a consistent and recurring issue that's been causing some problems for us over at Shields.io. 

Is it possible to get this API stabilized and/or is there a different API/query we could use to get the hit counts for a package/repo on a per year, week, and daily basis?

Thanks!

**Comment by MartinKolarik** [comment]
Hey, you mention a 524 error but the tests have a 5000 ms timeout. How do you know it actually responds with a 524?

**Comment by calebcartwright** [comment]
Hi @MartinKolarik thanks for the response! The tests do have a 5 second timeout, but I experienced the 524 error myself many times last night using other HTTP clients (not the Shields codebase/tests).

I can do this again later today and share the screenshot of the 524 error on your API I was receiving from CloudFlare in my web browser, and in Advanced Rest Client call last night if that would be helpful

**Comment by MartinKolarik** [comment]
> but I experienced the 524 error myself many times last night

Any chance this was between 00 - 01 AM UTC? The API is under higher load during that time, but for the rest of the day, our APM says all requests were under 10 seconds (and 95% of them under 500 ms).

**Comment by calebcartwright** [comment]
> Any chance this was between 00 - 01 AM UTC?

Yes, I _think_ that's when I was working with it yesterday. However, it also seems like we've been getting slow responses outside that time window (in particular 3:45 UTC). I'll increase our test timeout to 10 seconds during our recurring 3:45 UTC test run window and see if that makes a difference.

**Comment by MartinKolarik** [comment]
👍 we'll also be looking into ways to improve this.

**Comment by MartinKolarik** [comment]
I made some changes that should improve performance today (will see in a few hours) and there will most likely be some more in the next few days.

**Comment by calebcartwright** [comment]
That is excellent news @MartinKolarik, thanks so much!

**Comment by calebcartwright** [comment]
Wanted to share that so far we're seeing better performance/responsiveness over the last several days. We are still seeing fairly regular occurrences of timeouts (we're timing out after 10 seconds now) around ~3:45 UTC, but things definitely seem to be improving 👍

**Comment by MartinKolarik** [comment]
I believe we solved the last issue related to your daily builds today but will keep this open for a few more days until we can verify that. We made some major improvements in the past few days already and the API should be completely stable at any time now.

**Comment by calebcartwright** [comment]
Thanks again @MartinKolarik! The API has been working great for us for the last 3+ days now with no issues so I'm going to close this out.
