### ISSUE TITLE
500 & 524 on usage stats request

### ISSUE THREAD

**Issue by manferlo81** [jsdelivr/data.jsdelivr.com#14]
I am trying to get the usage stats for my package, I also tried the example on the readme page (https://data.jsdelivr.com/v1/package/npm/jquery/stats) and I am still getting a 500 Internal Server Error.

This is the actual response I am getting after a considerable amount of time (about a minute)

```json
{
	"status": 500,
	"message": "Internal Server Error"
}
```

A version list request (https://data.jsdelivr.com/v1/package/npm/jquery) works just fine...

```json
{
	"tags": {
		"beta": "3.4.1",
		"latest": "3.4.1"
	},
	"versions": [
		"3.4.1",
		"3.4.0",
		"3.3.1",
		"3.3.0",
		"3.2.1",
		"3.2.0",
		"3.1.1",
		"3.1.0",
		"3.0.0",
		"3.0.0-rc1",
		"3.0.0-beta1",
		"3.0.0-alpha1",
		"2.2.4",
		"2.2.3",
		"2.2.2",
		"2.2.1",
		"2.2.0",
		"2.1.4",
		"2.1.3",
		"2.1.2",
		"2.1.1",
		"2.1.1-rc2",
		"2.1.1-rc1",
		"2.1.1-beta1",
		"2.1.0",
		"2.1.0-rc1",
		"2.1.0-beta3",
		"2.1.0-beta2",
		"1.12.4",
		"1.12.3",
		"1.12.2",
		"1.12.1",
		"1.12.0",
		"1.11.3",
		"1.11.2",
		"1.11.1",
		"1.11.1-rc2",
		"1.11.1-rc1",
		"1.11.1-beta1",
		"1.11.0",
		"1.11.0-rc1",
		"1.11.0-beta3",
		"1.9.1",
		"1.8.3",
		"1.8.2",
		"1.7.3",
		"1.7.2",
		"1.6.3",
		"1.6.2",
		"1.5.1"
	]
}
```

Sometimes I also get a Error 524 from Cloudflare...

![screenshot](https://user-images.githubusercontent.com/11273138/58627721-14951a80-8302-11e9-836c-a9c150e4e99d.png)

I am from Indonesia, I also tried using a VPN from Singapore without success.

I don't really need this for any project right now, I just think it worth to notify you about the issue.

Thank you.

**Comment by manferlo81** [comment]
I also noticed the badge on my projects are, more often than not, failing to show, it may also be related to this issue.

**Comment by MartinKolarik** [comment]
Thanks for letting us know about this. There was an issue with the database used for storing stats, it should be ok now.
