### ISSUE TITLE
Rank badge

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/data.jsdelivr.com#21]
`jsDelivr rank | #1`

```
/package/npm/:name/badge/rank/:period?
/package/gh/:user/:repo/badge/rank/:period?
```

Implementation similar to the existing hits badge.

**Comment by jimaek** [comment]
@BirkhoffLee What do you think of this task? This is our main API. If you check the code and see improvements you would like to implement let us know as well

**Comment by BirkhoffLee** [comment]
After #274 get implemented I might look into this
