### ISSUE TITLE
Getting wrong files list

### ISSUE THREAD

**Issue by bruno12mota** [jsdelivr/data.jsdelivr.com#24]
Hey! Just noticed on a request to a package files list that there were files missing: https://data.jsdelivr.com/v1/package/npm/d3-hierarchy@1.1.9/flat

It's only showing two files when the package actually has way more as you can see here: https://unpkg.com/browse/d3-hierarchy@1.1.9/

Any way to spot what went wrong here? And also could you clear the cache for this specific index?

Thanks!

**Comment by MartinKolarik** [comment]
Hi, thanks for reporting this. It seems related to an issue with listings that we had for a few hours in November. We'll purge the CDN cache to refresh all responses shortly.

**Comment by bruno12mota** [comment]
Hey @MartinKolarik thanks so much for replying and for the help 👍
