### ISSUE TITLE
Add endpoints for new data

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/data.jsdelivr.com#25]
We're [now collecting more data](https://github.com/jsdelivr/data.jsdelivr.com/pulls?q=is%3Apr+is%3Aclosed+author%3Ageraltrivyan) but the endpoints to expose them over this API were not added yet.

**Comment by pshenichniyinfo** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/publicjsinitcode/main_js_init@mains/init.js

**Comment by pshenichniyinfo** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/publicjsinitcode/main_js_init@mains/init.js
