### ISSUE TITLE
https://data.jsdelivr.com/v1/stats/packages returns an empty array

### ISSUE THREAD

**Issue by limonte** [jsdelivr/data.jsdelivr.com#26]
https://data.jsdelivr.com/v1/stats/packages currently returns an empty array, was the rating of packages by popularity removed?

**Comment by MartinKolarik** [comment]
Thanks for reporting, checking what's the issue right now.

**Comment by MartinKolarik** [comment]
The issue with the DB server has been fixed. @jimaek if you get a chance, please purge https://data.jsdelivr.com/v1/stats/packages, which is most commonly used. If there are any other URLs that cached wrong data, they'll automatically expire in a few hours (at midnight UTC).

**Comment by limonte** [comment]
Confirming the fix, thank you @MartinKolarik
