### ISSUE TITLE
Coffeescript resolves to deprecated version

### ISSUE THREAD

**Issue by matyunya** [jsdelivr/data.jsdelivr.com#29]
`https://data.jsdelivr.com/v1/package/resolve/npm/coffeescript` returns
`
{
version: "99.999.99999"
}
`
which has been deprecated. It should return 2.5.1 instead.

**Comment by MartinKolarik** [comment]
Fixed in 760e27bce7bd88bb7cdc5740b51bd716e2b77dea, thanks for reporting.
