### ISSUE TITLE
Redis Persistence

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/data.jsdelivr.com#3]
Based on https://redis.io/topics/persistence the RDB method should work best for us. We want to cache all directory listings, as they can be expensive to generate, but loosing some data is OK (i.e. a snapshot every 24 hours is good enough).

**Comment by jimaek** [comment]
I am using https://www.compose.com/redis in persistent mode.
https://help.compose.com/docs/redis-cache-and-storage-modes

**Comment by jimaek** [comment]
What TTL are you using?

**Comment by MartinKolarik** [comment]
The page doesn't say much about those backups, but I guess if it somehow works, it works... No TTL for persistent keys.

**Comment by jimaek** [comment]
Well it doesn't really matter. Its only a cache, if we lose everything we will recreate the cache. Its not even worth restoring any backups
