### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by danny-laa** [jsdelivr/data.jsdelivr.com#30]
Can you add a license file for this project and also [jsdelivr/www.jsdelivr.com](https://github.com/jsdelivr/www.jsdelivr.com)?

**Comment by danny-laa** [comment]
@MartinKolarik Any news?

**Comment by MartinKolarik** [comment]
We're going to address this soon.

**Comment by MartinKolarik** [comment]
Added OSL 3.0 to both projects.
