### ISSUE TITLE
API CORS access issue via ByWave VPN

### ISSUE THREAD

**Issue by wlnirvana** [jsdelivr/data.jsdelivr.com#37]
**Describe the bug**
CORS error for data.jsdelivr.com domain

**Affected jsDelivr links**
https://www.jsdelivr.com/package/npm/swiper

**Response headers**
```
age: 202
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
cf-cache-status: HIT
cf-ray: 666b3832791f195f-HKG
cf-request-id: 0af6e173890000195f9f133000000001
content-length: 82
content-type: text/html; charset=utf-8
date: Tue, 29 Jun 2021 01:00:43 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
location: https://data.jsdelivr.com/v1/package/npm/swiper
nel: {"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=IACCOOPVNddm7kzzRgVDk1ABjHMW2xPkjK90yCyF0xLzmfOFYld7KKFfzmVrmoC%2FNFz%2FBQmKVY%2Bp7HsWBWrjJJ80CxHMf8CcYYn2UTph5FTLAOmtsqVOSKWSFsW%2FEDU%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Encoding
x-content-type-options: nosniff
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3822785/123721411-e2778d80-d8b8-11eb-9773-3916c5297535.png)

**Please complete the following information:**
 - Device OS: Windows 10 Pro 19041.1052
 - Browser: Microsoft Edge
 - Broser version: 91.0.864.59 (Official build) (64-bit)
 - VPN provider if you use one: ByWave
 - Your location (country): China

**Additional context**
If VPN is disconnected, the issue disappears. I guess the VPN vendor may have some proxy rules causing this problem but still this is weird because the VPN is a transparent proxy and the header is just missing. (The `access-control-allow-origin: *` header exists if VPN is disconnected.)

**Comment by jimaek** [comment]
We actually dont use Cloudflare on that domain. So no bot protection. It hits directly the hosting provider

**Comment by wlnirvana** [comment]
@MartinKolarik This is weird. Accessing https://data.jsdelivr.com/v1/package/npm/swiper directly returned the normal response:

```{
	"tags": {
		"latest": "6.7.1",
		"next": "6.0.0-alpha.18",
		"beta": "6.5.5-beta.1"
	},
	"versions": [
		"6.7.1",
		"6.7.0",
		"6.6.2",
...
```

**BUT THEN**,  all of sudden https://www.jsdelivr.com/package/npm/swiper started working, even when disable cache is selected. The response header for the ajax call to https://data.jsdelivr.com/v1/package/npm/swiper is now:

```
access-control-allow-origin: *
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
cache-control: public, max-age=300, stale-while-revalidate=3600, stale-if-error=43200
cf-cache-status: MISS
cf-ray: 6672bc6a1f51d1bf-HKG
cf-request-id: 0afb94164f0000d1bf263d5000000001
content-encoding: br
content-type: application/json; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Tue, 29 Jun 2021 22:54:20 GMT
etag: W/"6ff-kT8/OABKLpwx/BP8ObFtrtRtYS8"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=6RpQ8YZn2SimZvUVRCzYFm4ultAmRlj2rMtcknKIqbWpG1au8fcJsqAIVdcLpDfGBVUtuk8BBh7xltaAaWN5XE1o4di2ntjggFcuZnu%2B7Gwct0R%2BpLGz2iUnu7TAml0%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-content-type-options: nosniff
x-response-time: 7ms
```

**Comment by jimaek** [comment]
Any chance this is now fixed? Maybe the stuck DNS record wherever it was is now up to date?
