### ISSUE TITLE
System Down?

### ISSUE THREAD

**Issue by katehra-brc** [jsdelivr/data.jsdelivr.com#39]
The Data shows 0 for all Repos.

[![](https://data.jsdelivr.com/v1/package/npm/jquery/badge)](https://www.jsdelivr.com/package/npm/jquery)

**Comment by jimaek** [comment]
We're doing maintenance to our stats systems, everything should be back to normal soon

**Comment by jimaek** [comment]
Badges should be working now https://data.jsdelivr.com/v1/package/npm/jquery/badge
