### ISSUE TITLE
Support tag based file list lookups for listing package files

### ISSUE THREAD

**Issue by orta** [jsdelivr/data.jsdelivr.com#40]
e.g. I would like to request `https://data.jsdelivr.com/v1/package/npm/jquery@latest`

Today, I need to request:

- `https://data.jsdelivr.com/v1/package/npm/jquery` to get the info from the tags:
- which I can then use to call `https://data.jsdelivr.com/v1/package/npm/jquery@3.2.1`

**Comment by MartinKolarik** [comment]
This is very much on purpose to allow efficient caching because the result of the first call can't be cached almost at all while the result of the second call is immutable for exact versions.

**Comment by orta** [comment]
This makes a _lot_ of sense. I'll retract this because I strongly agree.
