### ISSUE TITLE
Support requesting only tags or versions on an npm versions list 

### ISSUE THREAD

**Issue by orta** [jsdelivr/data.jsdelivr.com#41]
Let's say I was looking up a tag for its version (re: #40) - I only need the tags, but the amount of data sent is pretty massive for any dependency which auto-deploys.

For example:  
 - https://data.jsdelivr.com/v1/package/npm/typescript 
 - https://data.jsdelivr.com/v1/package/npm/react

Perhaps query option:

 - https://data.jsdelivr.com/v1/package/npm/typescript?versions=false

**Comment by MartinKolarik** [comment]
Does [this](https://data.jsdelivr.com/v1/package/resolve/npm/jquery@beta) solve the problem? We mention only ranges in the readme but it resolves tags too. The intended use is that if you aren't sure you have a static version, you call the resolve endpoint and then anything else.

**Comment by orta** [comment]
That's everything I need, for sure 👍🏻 - just needs a mention in the readme then.

I almost sent the PR just now, but I don't know if the GitHub repo version of the API has the same behavior

**Comment by MartinKolarik** [comment]
Great! I updated the readme to explicitly mention this option for npm. GitHub doesn't have an equivalent of dist-tags so it doesn't apply there.

**Comment by orta** [comment]
Nope, closing this out 👍🏻 

Nice one!
