### ISSUE TITLE
500 Error when we trying to use packet info

### ISSUE THREAD

**Issue by Eddort** [jsdelivr/data.jsdelivr.com#42]
https://data.jsdelivr.com/v1/package/npm/jquery@3.2.1

This endpoint throws a 500 error. Yesterday this worked fine. Can you help with this problem?

**Comment by jimaek** [comment]
Our Digitalocean hosted DB is having issues, I am working on it

**Comment by jimaek** [comment]
This is it https://status.digitalocean.com/incidents/dg1fblqvb362

**Comment by jimaek** [comment]
Everything is back online

**Comment by jimaek** [comment]
We will continue monitoring just in case. We already had an internal task to improve the reliability of our API in cases such as this, we will make sure to implement it even faster.
