### ISSUE TITLE
How could I refresh my CDN cache?

### ISSUE THREAD

**Issue by SMARK2022** [jsdelivr/data.jsdelivr.com#47]
As we know, the cache has no time limit, so how can I refresh my CDN cache without a new release? Need I post an email to anyone? Thank you for helping me. :D

**Comment by CharlieS1103** [comment]
@SMARK2022 I might be wrong but the website said a cache purge is a WIP feature

**Comment by MartinKolarik** [comment]
If you mean changing an existing file without making a release, that's not possible (with exception of GH branches).
