### ISSUE TITLE
Version badge

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/data.jsdelivr.com#5]
Technically it'll always show the same version as a npm version badge, but several projects out there created their own "jsDelivr CDN version" badge, so it might be a good idea to support this (+ it should work with GitHub links too).

**Comment by styfle** [comment]
You might want to collaborate with @amio who runs https://badgen.net
There is already a version for [npm](https://badgen.net/npm/v/marked) and [github](https://badgen.net/github/release/markedjs/marked)

Maybe badgen could add the download stats badge now that I know there is a [stats api](https://github.com/jsdelivr/data.jsdelivr.com#get-package-usage-stats) 😄

**Comment by MartinKolarik** [comment]
This is fairly simple as we use a library that's behind https://shields.io/#/. You can even get such badge using their service right now: https://img.shields.io/npm/v/marked.svg?label=jsDelivr. The idea was just including it directly in this API.

**Comment by styfle** [comment]
I see.

Badgen is typically faster and the API is very similar as you can see here: https://badgen.net/npm/v/marked?label=jsDelivr&color=ff5627

If you want to render it yourself, you can use the [badgen](https://www.npmjs.com/package/badgen) package which is what the web app uses.

**Comment by amio** [comment]
That's partially because PackagePhobia doesn't provide a flat style badge 😄

+1 for the "one-stop shop". But further discussion on this is a bit off-topic, we may continue this on amio/badgen-service#193
