### ISSUE TITLE
Cannot fetch with named version a.k.a `@latest`

### ISSUE THREAD

**Issue by softmarshmallow** [jsdelivr/data.jsdelivr.com#52]
Fetching the latest version's data.

`https://data.jsdelivr.com/v1/package/npm/react@latest` -> 404

Which react does have a `latest` tag, https://data.jsdelivr.com/v1/package/npm/react

<img width="607" alt="Screen Shot 2022-11-05 at 3 12 40 AM" src="https://user-images.githubusercontent.com/16307013/200046472-3b3b9687-fe72-4634-ab12-314473ef50b7.png">

**Comment by MartinKolarik** [comment]
> Make sure you use a specific version number, and not a version range or an npm tag

You should request it as https://data.jsdelivr.com/v1/package/npm/react@18.2.0. If you don't know the version in advance, call https://data.jsdelivr.com/v1/package/resolve/npm/react first.
