### ISSUE TITLE
Incorrectly showing CSS file

### ISSUE THREAD

**Issue by arshaw** [jsdelivr/data.jsdelivr.com#53]
For recent versions of [fullcalendar](https://www.jsdelivr.com/package/npm/fullcalendar?version=6.1.0), the `https://cdn.jsdelivr.net/npm/fullcalendar/main.min.css` is being advertised when in fact its part of an old version of the package. The current version of the package (6.1.0) does not have CSS files anymore. This is confusing our users a bit!

PS- I love the recent redesign of the site. Very slick.

**Comment by MartinKolarik** [comment]
Fixed: https://www.jsdelivr.com/package/npm/fullcalendar
