### ISSUE TITLE
Searching jsdelivr.com for a package

### ISSUE THREAD

**Issue by gujiman** [jsdelivr/data.jsdelivr.com#6]
Is it possible to search jsdelivr.com for a package, for example like the search engine on the main https://www.jsdelivr.com page?

An api uasge example would be:

https://data.jsdelivr.com/v1/package/npm?search=jqu 

would result in "jquery, ..."

**Comment by MartinKolarik** [comment]
Yes, there's a separate API for that, powered by [Algolia](https://www.algolia.com/). You can check the [jsdelivr.com code](https://github.com/jsdelivr/www.jsdelivr.com/blob/master/src/public/js/utils/search.js) for an usage example, [Algolia's repo](https://github.com/algolia/npm-search#schema) for full information about the data, and [their API docs](https://www.algolia.com/doc/api-reference/api-methods/search/) for all supported methods and options.

**Comment by gujiman** [comment]
@MartinKolarik Just a quick question, i can get the search working, but i was wondering can anyone use your algolia api key "f54e21fa3a2a0160595bb058179bfb1e" or are they required to get their own key?

https://github.com/jsdelivr/www.jsdelivr.com/blob/master/src/public/js/utils/search.js#L2

**Comment by MartinKolarik** [comment]
Yep, consider it a public key for anyone to use.
