### ISSUE TITLE
Server incorrectly advertises HTTP/3 support

### ISSUE THREAD

**Issue by limzykenneth** [jsdelivr/data.jsdelivr.com#61]
I'm still exploring HTTP/3 (and QUIC) so I may misunderstand something here, but as far as I can tell, https://data.jsdelivr.com seems to be advertising support for HTTP/3 protocol with the `alt-svc : h3=":443"` header. However attempting to make a QUIC connection to the server does not seem to be working.

Checking on a [testing site](https://domsignal.com/test/zx0mrs9105p9c2w9yx72yry4gapdihfe) also seem to indicate that HTTP/3 support is not available on the server.

It would be great that if the server does not support HTTP/3 it should not send the `alt-svc` header with the `h3` value, or even better to enable support of HTTP/3 for the server (the https://cdn.jsdelivr.net host seems to already have good HTTP/3 support already for example).

**Comment by MartinKolarik** [comment]
@jimaek can we either enable HTTP/3 at Bunny if they support it, or configure it to drop `Alt-Svc` header from all responses?

**Comment by jimaek** [comment]
They dont support it yet so I removed the header

**Comment by limzykenneth** [comment]
Great, not seeing the header anymore. Would be nice to have it added back whenever BunnyCDN start supporting HTTP/3 but this will do for now. Thanks for getting on it so quickly.
